-- Baseline do schema do MyoTrack, transcrito do estado final das migrations do EF Core
-- (backend/MyoTrack.Infrastructure/Migrations/AppDbContextModelSnapshot.cs, ProductVersion 9.0.18).
--
-- Em um banco que JÁ existe (produção/desenvolvimento com o .NET), o Flyway roda com
-- baseline-on-migrate=true e NUNCA executa este script — ele só documenta o ponto de partida
-- e serve para criar bancos novos (testes, CI, máquina limpa).
--
-- Os identificadores são PascalCase entre aspas porque é assim que o Npgsql os criou:
-- no Postgres, identificador sem aspas é dobrado para minúsculo e não casaria com o schema atual.

-- ---------------------------------------------------------------------------
-- Identity (ASP.NET Core Identity com chave Guid)
-- ---------------------------------------------------------------------------

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "DisplayName" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

-- ---------------------------------------------------------------------------
-- Sessão (tokens próprios, fora do Identity)
-- ---------------------------------------------------------------------------

CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

-- Código de uso único do login com Google (a SPA nunca recebe tokens na URL).
CREATE TABLE "LoginCodes" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CodeHash" character varying(64) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    CONSTRAINT "PK_LoginCodes" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_LoginCodes_CodeHash" ON "LoginCodes" ("CodeHash");

-- ---------------------------------------------------------------------------
-- Perfil e consentimento (LGPD)
-- ---------------------------------------------------------------------------

CREATE TABLE "UserProfiles" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "BirthDate" date,
    "Sex" text,
    "HeightCm" numeric,
    "Biotype" integer,
    "ExperienceLevel" integer NOT NULL,
    "Goal" integer NOT NULL,
    "TrainingDaysPerWeek" integer NOT NULL,
    "PriorityMuscleGroups" integer[] NOT NULL,
    "InjuryNotes" text,
    "InjuryTags" text[] NOT NULL,
    "AvailableEquipment" integer[] NOT NULL,
    "DietaryRestrictions" text[] NOT NULL,
    "FoodPreferences" text[] NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_UserProfiles_UserId" ON "UserProfiles" ("UserId");

CREATE TABLE "ConsentRecords" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" integer NOT NULL,
    "TermsVersion" text NOT NULL,
    "GrantedAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_ConsentRecords" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_ConsentRecords_UserId_Type" ON "ConsentRecords" ("UserId", "Type");

-- ---------------------------------------------------------------------------
-- Catálogos (semeados no startup: exercícios e alimentos TACO)
-- ---------------------------------------------------------------------------

CREATE TABLE "Exercises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "PrimaryMuscleGroup" integer NOT NULL,
    "SecondaryMuscleGroups" integer[] NOT NULL,
    "Equipment" integer NOT NULL,
    "IsCompound" boolean NOT NULL,
    "ContraindicationTags" text[] NOT NULL,
    "Instructions" text,
    "MediaUrl" text,
    "TutorialVideoUrl" character varying(500),
    CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Exercises_Name" ON "Exercises" ("Name");

CREATE TABLE "FoodItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(300) NOT NULL,
    "Source" text NOT NULL,
    "KcalPer100g" numeric NOT NULL,
    "ProteinPer100g" numeric NOT NULL,
    "CarbsPer100g" numeric NOT NULL,
    "FatPer100g" numeric NOT NULL,
    "FiberPer100g" numeric,
    CONSTRAINT "PK_FoodItems" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_FoodItems_Name" ON "FoodItems" ("Name");

-- ---------------------------------------------------------------------------
-- Plano de treino
-- ---------------------------------------------------------------------------

CREATE TABLE "WorkoutPlans" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Goal" integer NOT NULL,
    "Split" text NOT NULL,
    "Status" integer NOT NULL,
    "Version" integer NOT NULL,
    "GenerationInputJson" jsonb,
    "RawLlmOutputJson" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    -- O DEFAULT veio do ALTER TABLE da migration que introduziu a revisão humana: a coluna é
    -- NOT NULL e precisava de um valor para as linhas que já existiam.
    "ReviewStatus" integer DEFAULT 0 NOT NULL,
    "ReviewedByUserId" uuid,
    "ReviewNote" text,
    "ReviewedAt" timestamp with time zone,
    CONSTRAINT "PK_WorkoutPlans" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_WorkoutPlans_UserId_Status" ON "WorkoutPlans" ("UserId", "Status");

CREATE TABLE "WorkoutDays" (
    "Id" uuid NOT NULL,
    "WorkoutPlanId" uuid NOT NULL,
    "Order" integer NOT NULL,
    "Label" text NOT NULL,
    CONSTRAINT "PK_WorkoutDays" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkoutDays_WorkoutPlans_WorkoutPlanId" FOREIGN KEY ("WorkoutPlanId")
        REFERENCES "WorkoutPlans" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WorkoutDays_WorkoutPlanId" ON "WorkoutDays" ("WorkoutPlanId");

CREATE TABLE "WorkoutExercises" (
    "Id" uuid NOT NULL,
    "WorkoutDayId" uuid NOT NULL,
    "ExerciseId" integer NOT NULL,
    "Order" integer NOT NULL,
    "Sets" integer NOT NULL,
    "RepsMin" integer NOT NULL,
    "RepsMax" integer NOT NULL,
    "SuggestedLoadKg" numeric,
    "RestSeconds" integer NOT NULL,
    "Notes" text,
    CONSTRAINT "PK_WorkoutExercises" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorkoutExercises_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId")
        REFERENCES "Exercises" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WorkoutExercises_WorkoutDays_WorkoutDayId" FOREIGN KEY ("WorkoutDayId")
        REFERENCES "WorkoutDays" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WorkoutExercises_ExerciseId" ON "WorkoutExercises" ("ExerciseId");
CREATE INDEX "IX_WorkoutExercises_WorkoutDayId" ON "WorkoutExercises" ("WorkoutDayId");

-- ---------------------------------------------------------------------------
-- Execução de treino
-- ---------------------------------------------------------------------------

CREATE TABLE "WorkoutSessions" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "WorkoutDayId" uuid,
    "Date" date NOT NULL,
    "Notes" text,
    CONSTRAINT "PK_WorkoutSessions" PRIMARY KEY ("Id"),
    -- Sem ON DELETE: a relação é opcional e o EF gerou NO ACTION (a checagem fica para o fim da
    -- transação). RESTRICT checaria na hora e não é o que o banco atual tem.
    CONSTRAINT "FK_WorkoutSessions_WorkoutDays_WorkoutDayId" FOREIGN KEY ("WorkoutDayId")
        REFERENCES "WorkoutDays" ("Id")
);

CREATE INDEX "IX_WorkoutSessions_WorkoutDayId" ON "WorkoutSessions" ("WorkoutDayId");
CREATE INDEX "IX_WorkoutSessions_UserId_Date" ON "WorkoutSessions" ("UserId", "Date");

CREATE TABLE "SetLogs" (
    "Id" uuid NOT NULL,
    "WorkoutSessionId" uuid NOT NULL,
    "ExerciseId" integer NOT NULL,
    "SetNumber" integer NOT NULL,
    "Reps" integer NOT NULL,
    "LoadKg" numeric NOT NULL,
    "Rpe" integer,
    CONSTRAINT "PK_SetLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SetLogs_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId")
        REFERENCES "Exercises" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SetLogs_WorkoutSessions_WorkoutSessionId" FOREIGN KEY ("WorkoutSessionId")
        REFERENCES "WorkoutSessions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_SetLogs_ExerciseId" ON "SetLogs" ("ExerciseId");
CREATE INDEX "IX_SetLogs_WorkoutSessionId" ON "SetLogs" ("WorkoutSessionId");

CREATE TABLE "BodyMeasurements" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Date" date NOT NULL,
    "WeightKg" numeric,
    "BodyFatPercent" numeric,
    "ChestCm" numeric,
    "WaistCm" numeric,
    "HipCm" numeric,
    "ArmCm" numeric,
    "ThighCm" numeric,
    "CalfCm" numeric,
    CONSTRAINT "PK_BodyMeasurements" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_BodyMeasurements_UserId_Date" ON "BodyMeasurements" ("UserId", "Date");

-- ---------------------------------------------------------------------------
-- Plano de dieta
-- ---------------------------------------------------------------------------

CREATE TABLE "DietPlans" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Name" text NOT NULL,
    "CalorieGoal" integer NOT NULL,
    "Status" integer NOT NULL,
    "Version" integer NOT NULL,
    "TargetKcal" numeric NOT NULL,
    "TargetProteinG" numeric NOT NULL,
    "TargetCarbsG" numeric NOT NULL,
    "TargetFatG" numeric NOT NULL,
    "GenerationInputJson" jsonb,
    "RawLlmOutputJson" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    -- Mesmo motivo do WorkoutPlans.ReviewStatus.
    "ReviewStatus" integer DEFAULT 0 NOT NULL,
    "ReviewedByUserId" uuid,
    "ReviewNote" text,
    "ReviewedAt" timestamp with time zone,
    CONSTRAINT "PK_DietPlans" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_DietPlans_UserId_Status" ON "DietPlans" ("UserId", "Status");

CREATE TABLE "Meals" (
    "Id" uuid NOT NULL,
    "DietPlanId" uuid NOT NULL,
    "Order" integer NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Meals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Meals_DietPlans_DietPlanId" FOREIGN KEY ("DietPlanId")
        REFERENCES "DietPlans" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Meals_DietPlanId" ON "Meals" ("DietPlanId");

CREATE TABLE "MealItems" (
    "Id" uuid NOT NULL,
    "MealId" uuid NOT NULL,
    "FoodItemId" integer NOT NULL,
    "QuantityG" numeric NOT NULL,
    CONSTRAINT "PK_MealItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MealItems_FoodItems_FoodItemId" FOREIGN KEY ("FoodItemId")
        REFERENCES "FoodItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MealItems_Meals_MealId" FOREIGN KEY ("MealId")
        REFERENCES "Meals" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_MealItems_FoodItemId" ON "MealItems" ("FoodItemId");
CREATE INDEX "IX_MealItems_MealId" ON "MealItems" ("MealId");

-- ---------------------------------------------------------------------------
-- Fila de jobs de IA e resultados das análises
-- ---------------------------------------------------------------------------

CREATE TABLE "AnalysisJobs" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "MediaKey" text,
    "InputJson" jsonb,
    "ResultJson" jsonb,
    "LastError" text,
    "Attempts" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    CONSTRAINT "PK_AnalysisJobs" PRIMARY KEY ("Id")
);

-- O worker busca o job pendente mais antigo com FOR UPDATE SKIP LOCKED.
CREATE INDEX "IX_AnalysisJobs_Status_CreatedAt" ON "AnalysisJobs" ("Status", "CreatedAt");

CREATE TABLE "MealPhotoAnalyses" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AnalysisJobId" uuid NOT NULL,
    "MediaKey" text NOT NULL,
    "IllustratedMediaKey" text,
    "ItemsJson" jsonb NOT NULL,
    "TotalKcal" numeric NOT NULL,
    "TotalProteinG" numeric NOT NULL,
    "TotalCarbsG" numeric NOT NULL,
    "TotalFatG" numeric NOT NULL,
    "UserAdjusted" boolean NOT NULL,
    -- DEFAULT herdado do ALTER TABLE da migration do diário alimentar.
    "ExcludedFromDiary" boolean DEFAULT false NOT NULL,
    "MediaExpiredAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MealPhotoAnalyses" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_MealPhotoAnalyses_AnalysisJobId" ON "MealPhotoAnalyses" ("AnalysisJobId");
CREATE INDEX "IX_MealPhotoAnalyses_UserId_CreatedAt" ON "MealPhotoAnalyses" ("UserId", "CreatedAt");

CREATE TABLE "ExerciseVideoAnalyses" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "AnalysisJobId" uuid NOT NULL,
    "MediaKey" text NOT NULL,
    "OverlayVideoKey" text,
    "AnalyzedExercise" character varying(50) NOT NULL,
    "RepCount" integer NOT NULL,
    "Score" integer,
    "ResultJson" jsonb NOT NULL,
    "MediaExpiredAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExerciseVideoAnalyses" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_ExerciseVideoAnalyses_AnalysisJobId" ON "ExerciseVideoAnalyses" ("AnalysisJobId");
CREATE INDEX "IX_ExerciseVideoAnalyses_UserId_CreatedAt" ON "ExerciseVideoAnalyses" ("UserId", "CreatedAt");

CREATE TABLE "AiUsageLogs" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Operation" integer NOT NULL,
    "Model" text NOT NULL,
    "InputTokens" bigint NOT NULL,
    "OutputTokens" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AiUsageLogs" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_AiUsageLogs_UserId_CreatedAt" ON "AiUsageLogs" ("UserId", "CreatedAt");

-- ---------------------------------------------------------------------------
-- Engajamento (coach e relatório semanal)
-- ---------------------------------------------------------------------------

CREATE TABLE "CoachMessages" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "FromUser" boolean NOT NULL,
    "Content" character varying(4000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CoachMessages" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_CoachMessages_UserId_CreatedAt" ON "CoachMessages" ("UserId", "CreatedAt");

CREATE TABLE "WeeklyReports" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "WeekStart" date NOT NULL,
    "MetricsJson" jsonb NOT NULL,
    "NarrativeJson" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WeeklyReports" PRIMARY KEY ("Id")
);

-- Uma linha por usuário/semana: o scheduler roda 1 vez por semana e é idempotente.
CREATE UNIQUE INDEX "IX_WeeklyReports_UserId_WeekStart" ON "WeeklyReports" ("UserId", "WeekStart");

-- ---------------------------------------------------------------------------
-- Billing (Stripe)
-- ---------------------------------------------------------------------------

CREATE TABLE "UserSubscriptions" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Plan" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "StripeCustomerId" text,
    "StripeSubscriptionId" text,
    "StripeStatus" character varying(50),
    "CurrentPeriodEnd" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserSubscriptions" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_UserSubscriptions_UserId" ON "UserSubscriptions" ("UserId");
CREATE INDEX "IX_UserSubscriptions_StripeCustomerId" ON "UserSubscriptions" ("StripeCustomerId");
CREATE INDEX "IX_UserSubscriptions_StripeSubscriptionId" ON "UserSubscriptions" ("StripeSubscriptionId");

-- Idempotência dos webhooks: o Stripe reenvia o mesmo evento em caso de falha.
CREATE TABLE "StripeEventLogs" (
    "Id" character varying(255) NOT NULL,
    "Type" character varying(100) NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StripeEventLogs" PRIMARY KEY ("Id")
);
